### ISSUE TITLE
Inconsistency about the `/ColorSpace` entry for embedded JPEG images

### ISSUE THREAD

**Issue by gfngfn** [gfngfn/SATySFi#31] opened 2018-02-14 06:46 UTC
https://twitter.com/kurgm/status/963657925402165249

**Comment by sakas--** [comment] 2018-03-31 04:27
I had a look at this problem.
The problem is due to the fact that `header_infos` returned by CamlImages is always `[]` when a jpeg image is read.  
I'm going to send a PR, which should fix this problem, to CamlImages in the near future.

**Comment by sakas--** [comment] 2018-03-31 05:50
I created a PR.
(https://bitbucket.org/camlspotter/camlimages/pull-requests/4/add-colormodel-to-header_infos-when-a-jpeg/diff)

Let's wait for a reaction.

**Comment by sakas--** [comment] 2018-04-02 13:59
The PR has been merged!
Next steps:
- [ ] Wait until opam approves the PR from camlimages. (https://github.com/ocaml/opam-repository/pull/11715)
- [ ] Check whether we can unpin camlimages and use the latest version.
- [ ] Write a patch that fixes this issue.

BTW, I don't think that fixing this issue is very important, so there's no need to hurry.

**Closed** 2018-04-04 07:00 UTC
Labels: bug
